name: Update PluginMaster

on: 
  push:
    paths-ignore:
      - '**.md'
      - pluginmaster.json

    branches:
      - master

  workflow_dispatch:

concurrency:
  this_is_concurrency_workflow

env:
  DOWNLOAD_BASE_URI: https://repo.horoscope.dev

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Update PluginMaster (stable)
        run: python update.py
        env:
          DALAMUD_ENV: stable
          DOWNLOAD_BASE_URI: ${{ env.DOWNLOAD_BASE_URI }}

      - name: Update PluginMaster (testing)
        run: python update.py
        env:
          DALAMUD_ENV: testing
          DOWNLOAD_BASE_URI: ${{ env.DOWNLOAD_BASE_URI }}

      - name: Push PluginMaster
        uses: EndBug/add-and-commit@v7
        with:
          author_name: GitHub Action
          author_email: github-actions[bot]@users.noreply.github.com
          message: Update PluginMaster
