name: Update PluginMaster

on: 
  push:
    paths-ignore:
      - '**.md'
      - pluginmaster.json

    branches:
      - master

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Update PluginMaster (stable)
        run: python update.py
        env:
          DALAMUD_ENV: stable

      - name: Update PluginMaster (testing)
        run: python update.py
        env:
          DALAMUD_ENV: testing

      - name: Push PluginMaster
        uses: EndBug/add-and-commit@v7
        with:
          author_name: GitHub Action
          author_email: github-actions[bot]@users.noreply.github.com
          message: Update PluginMaster
