name: Update PluginMaster

env:
  DOWNLOAD_BASE_URI: https://repo.horoscope.dev

on: 
  push:
    paths-ignore:
      - '**.md'
      - '**/pluginmaster.json'

    branches:
      - master

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    concurrency: staging
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Update PluginMaster (stable)
        run: python update.py
        env:
          DALAMUD_ENV: stable
          DOWNLOAD_BASE_URI: ${{ env.DOWNLOAD_BASE_URI }}

      - name: Update PluginMaster (testing)
        run: python update.py
        env:
          DALAMUD_ENV: testing
          DOWNLOAD_BASE_URI: ${{ env.DOWNLOAD_BASE_URI }}

      - name: Push PluginMaster
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: Regenerate PluginMaster
